#!/usr/bin/bash

stow_options="--verbose 1 -t $HOME --restow"

stow $stow_options nvim

if [[ $(hostnamectl hostname) = 'nautilus' ]]; then
     stow $stow_options desktop
     stow $stow_options bash
elif [[ $(hostnamectl hostname) = 'sancho' ]]; then
     stow $stow_options laptop
     stow $stow_options sway
     stow $stow_options zsh
fi
