#!/usr/bin/bash

stow_options="-n -t $HOME"

stow $stow_options zsh
stow $stow_options vim
stow $stow_options sway
stow -t $HOME nvim

if [[ $(hostnamectl hostname) = 'nautilus' ]]; then
	stow -t $HOME desktop
	stow -t $HOME bash 
elif [[ $(hostnamectl hostname) = 'uranus' ]]; then
     stow $stow_options laptop
fi
