#!/usr/bin/bash

stow_options="-t $HOME"

echo "$stow_options"
stow $stow_options nvim

if [[ $(hostnamectl hostname) = 'nautilus' ]]; then
     stow $stow_options desktop
elif [[ $(hostnamectl hostname) = 'sancho' ]]; then
     echo "$stow_options"
     stow $stow_options laptop
     stow $stow_options sway
     stow $stow_options zsh
fi
